### PR TITLE
chore(deps): fix security vulnerabilities

### PR DESCRIPTION
**Pull request by kilchenmann**
incl. upgrade to angular v13 in test-environment

### CODE REVIEW

**Review by mdelez — APPROVED** [review]
Thank you for keeping js-lib safe :)

**Comment by kilchenmann** [comment]
oh no... I was too fast. I forgot to push my changes regarding the angular update to v13 🙈

**Comment by mdelez** [comment]
> oh no... I was too fast. I forgot to push my changes regarding the angular update to v13 🙈

oops 🙈 will you open another PR for that?

**Comment by kilchenmann** [comment]
> will you open another PR for that?

not sure at the moment. everything seems to be broken now

**Pull request merged**
