### PR TITLE
feat(ontologies-endpoint): updateOntology method (DSP-1358)

### PR DESCRIPTION
**Pull request by mdelez**
resolves DSP-1358

### CODE REVIEW

**Comment by mdelez** [comment]
e2e tests on github-ci require this PR https://github.com/dasch-swiss/dsp-api/pull/1826. Waiting on a new DSP-API release which contains this PR.

**Comment by kilchenmann** [comment]
I will test this PR in my DSP-APP "update ontology branch"

**Comment by kilchenmann** [comment]
@mdelez `comment` is still missing in `CreateOntology` object. Could you add the following lines to it:

```typescript
    @JsonProperty(Constants.Comment, String)
    comment: string = "";
```

**Comment by kilchenmann** [comment]
@mdelez I saw you updated `OntologyMetadata` with `comment` but not the `CreateOntology` object. It's defined in task DSP-1357, but I think you can resolve it in the same PR

**Comment by mdelez** [comment]
> @mdelez `comment` is still missing in `CreateOntology` object. Could you add the following lines to it:
> 
> ```ts
>     @JsonProperty(Constants.Comment, String)
>     comment: string = "";
> ```

Sure thing! Should it be optional?

**Comment by kilchenmann** [comment]
> > @mdelez `comment` is still missing in `CreateOntology` object. Could you add the following lines to it:
> > ```ts
> >     @JsonProperty(Constants.Comment, String)
> >     comment: string = "";
> > ```
> 
> Sure thing! Should it be optional?

Yes, I think it could be optional.

**Comment by mdelez** [comment]
> Yes, I think it could be optional.

done in 4b95ebd :)

**Review by kilchenmann — APPROVED** [review]

**Pull request merged**
