### PR TITLE
Prerelease v1.0.0-rc.12

### PR DESCRIPTION
**Pull request by kilchenmann**
Prepare next prerelease rc.12

### CODE REVIEW

**Review by tobiasschweizer — APPROVED** [review]
Ok!

Will you also make a new release of dsp-ui?

**Comment by kilchenmann** [comment]
> Will you also make a new release of dsp-ui?

Yes of course. It's all part of DSP-672 and DSP-673

**Comment by tobiasschweizer** [comment]
> > Will you also make a new release of dsp-ui?
> 
> Yes of course. It's all part of DSP-672 and DSP-673

just remember to adapt the makefile this time ;-)

**Comment by kilchenmann** [comment]
> just remember to adapt the makefile this time ;-)

Yes, I will follow the new step-by-step documentation in README 😉

**Pull request merged**
