### PR TITLE
DSP-702 Add template for PRs

### PR DESCRIPTION
**Pull request by kilchenmann**
resolves [DSP-702](https://dasch.myjetbrains.com/youtrack/issue/DSP-702)

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
Sorry, I don't understand how this template would be used.

**Comment by kilchenmann** [comment]
It will create an automated PR description with a link to youtrack. The PR creator has to update only the title and the xy in the description.

I followed this documentation:
<https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository>

**Comment by kilchenmann** [comment]
We already implemented it in dsp-app and it works very well

**Review by tobiasschweizer — APPROVED** [review]
ok, thanks for the explanation

**Pull request merged**
