### PR TITLE
chore(project-metadata): remove project metadata implementation (DEV-282)

### PR DESCRIPTION
**Pull request by mdelez**
resolves DEV-282

### CODE REVIEW

**Comment by mdelez** [comment]
@mpro7 I'm not sure if everything related to `IUrl` is part of the metadata. Do you know if it can also be removed?

**Comment by mpro7** [comment]
@mdelez as far as I remember I've created it while adding metadata related stuff and it was only used there.

**Comment by mdelez** [comment]
@mpro7 ok, then I will remove it

**Comment by mpro7** [comment]
@mdelez you can also remove (unless you will find some usage):
`src/interfaces/models/v2/project-metadata-interfaces.ts`
and from below location
`../models/v2/custom-converters/`
- all `union-` converters
- distribution-converter
- place-converter
- id-converter

**Review by mpro7 — APPROVED** [review]
Ok I think you already did what I've asked in prev comment.

**Pull request merged**
