### PR TITLE
fix(endpoint)!: resolve set-cookie issue (DSP-1827)

### PR DESCRIPTION
**Pull request by kilchenmann**
resolves DSP-1827

### CODE REVIEW

**Comment by kilchenmann** [comment]
This is how it works now:

**Comment by kilchenmann** [comment]
btw. for the reviewers: if you want to test it with the test-framework you have to open it on the same domain as the api is running e.g. http://0.0.0.0:4200 and you should see the cookie in the request headers if it was set on login.

Screen Shot 2021-07-28 at 12 14 30

**Review by subotic — APPROVED** [review]
Great, thanks! LGTM

**Comment by kilchenmann** [comment]
> Edit: Or we could set crossDomain to true? Not sure if this works. I'll try after lunch....

No, crossDomain does not work. Not sure if it's supported from the API-side!?

**Review by mdelez — APPROVED** [review]
works well!

**Pull request merged**
